- name: Create Config file
  ansible.builtin.template:
    src: m-jab.xml
    dest: /tmp/m-jab.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)


- name: Create Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-jab.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.8.248:8080
    user: admin
    password: "{{jenkins_password}}"
