- name: Create Config file
  ansible.builtin.template:
    src: s-jab.xml
    dest: /tmp/s-jab.xml

- name: Create Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-jab.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.8.248:8080
    user: admin
    password: "{{jenkins_password}}"
